// GENERATED by cmd/golden6. Do not edit by hand.
//
// Pins the six games added by migration 000032 to the Go engines they mirror.
// The logs below were played by a bot against the Go implementation; replaying
// them here has to produce the identical score and stats. A difference means
// the app would show a player one number and the server would bank another.

import 'package:flutter_test/flutter_test.dart';

import 'package:send_agift_mobile/features/games/domain/bubble_shooter.dart';
import 'package:send_agift_mobile/features/games/domain/doodle_jump.dart';
import 'package:send_agift_mobile/features/games/domain/fruit_slice.dart';
import 'package:send_agift_mobile/features/games/domain/memory_match.dart';
import 'package:send_agift_mobile/features/games/domain/tower_blocks.dart';
import 'package:send_agift_mobile/features/games/domain/whack_a_mole.dart';

const seed = '5f3a91c2';

void main() {
  test('memory match matches the Go engine', () {
    // Go: score=440 best_streak=8 matches=8 turns=9
    // Pinned against the original 4x4 (8-pair) config explicitly. Memory
    // Match's default has since grown to a 6x6 board, but the log was
    // captured on the smaller one and must keep replaying on it.
    const moves = [
      '4',
      '1',
      '4',
      '11',
      '1',
      '2',
      '5',
      '6',
      '8',
      '14',
      '12',
      '15',
      '7',
      '10',
      '0',
      '9',
      '3',
      '13',
    ];
    final game = MemoryMatch(
      seed: seed,
      config: const MemoryConfig(pairs: 8, columns: 4, maxTurns: 80),
    );
    for (final move in moves) {
      game.flip(int.parse(move));
    }
    expect(game.score, 440);
    expect(game.matches, 8);
    expect(game.turns, 9);
    expect(game.bestStreak, 8);
    expect(game.moves, moves);
  });

  test('whack-a-mole matches the Go engine', () {
    // Go: score=2304 best_streak=32 hits=32 misses=0
    const moves = [
      '10:1',
      '68:0',
      '131:4',
      '238:0',
      '296:2',
      '347:7',
      '399:2',
      '500:0',
      '553:0',
      '605:1',
      '650:8',
      '745:3',
      '791:6',
      '840:3',
      '886:3',
      '971:0',
      '1010:4',
      '1050:8',
      '1093:7',
      '1168:4',
      '1200:8',
      '1239:8',
      '1275:8',
      '1338:8',
      '1373:2',
      '1403:0',
      '1435:0',
      '1497:6',
      '1527:7',
      '1557:7',
      '1591:7',
      '1655:3',
    ];
    final game = WhackAMole(seed: seed, config: const WhackConfig());
    for (final move in moves) {
      final parts = move.split(':');
      final at = int.parse(parts[0]);
      while (game.tick < at && !game.isOver) {
        game.advance();
      }
      game.whack(int.parse(parts[1]));
    }
    expect(game.score, 2304);
    expect(game.hits, 32);
    expect(game.bestStreak, 32);
    expect(game.moves, moves);
  });

  test('bubble shooter matches the Go engine', () {
    // Go: score=810 pops=71 shots=60 best_combo=1
    //
    // A mix of aims. Sideways units per 1000 of rise, so the flight banks
    // off the walls. And 's' swaps of the two queued colours. Played by a
    // bot that takes the best shot on offer: firing at random on this seed
    // pops nothing at all, so matching here means the flight physics and the
    // queue both step identically to the Go engine.
    const moves = [
      '-4000',
      '-4000',
      '-4000',
      's',
      '-3400',
      's',
      '-3000',
      's',
      '-3000',
      '-3200',
      's',
      '-1000',
      's',
      '-1000',
      '-4000',
      's',
      '-4000',
      '-4000',
      '-4000',
      's',
      '-2800',
      '-4000',
      '-4000',
      's',
      '-2600',
      '-4000',
      's',
      '-2600',
      's',
      '-3600',
      's',
      '-1800',
      '-600',
      's',
      '-800',
      '-4000',
      '-4000',
      's',
      '-3400',
      '-4000',
      '-4000',
      '-4000',
      '-4000',
      '-4000',
      's',
      '-3600',
      '-4000',
      '-4000',
      's',
      '-3800',
      '-4000',
      '-4000',
      's',
      '-2600',
      '-4000',
      '-4000',
      's',
      '-2800',
      '-4000',
      '-4000',
      's',
      '-3200',
      '-4000',
      '-4000',
      '-4000',
      '-4000',
      '-4000',
      '-4000',
      '-4000',
      '-4000',
      '-4000',
      '-4000',
      '-4000',
      '-4000',
      '-4000',
      '-4000',
      '-4000',
      '-4000',
    ];
    final game = BubbleShooter(seed: 'cafebabe', config: const BubbleConfig());
    for (final move in moves) {
      if (move == bubbleSwapMove) {
        game.swap();
      } else {
        game.shoot(int.parse(move));
      }
    }
    expect(game.score, 810);
    expect(game.pops, 71);
    expect(game.shots, 60);
    expect(game.bestCombo, 1);
    expect(game.isOver, isFalse);
    expect(game.moves, moves);
  });

  test('tower blocks matches the Go engine', () {
    // Go: score=640 best_combo=1 placed=40 rows=12
    const moves = [
      '0',
      '2',
      '4',
      '0',
      '3',
      '0',
      '5',
      '5',
      '2',
      '3',
      '0',
      '3',
      '4',
      '0',
      '3',
      '0',
      '1',
      '2',
      '5',
      '0',
      '3',
      '4',
      '0',
      '2',
      '0',
      '3',
      '0',
      '3',
      '5',
      '5',
      '0',
      '1',
      '4',
      '0',
      '5',
      '3',
      '5',
      '0',
      '1',
      '2',
    ];
    final game = TowerBlocks(seed: seed, config: const TowerBlocksConfig());
    for (final move in moves) {
      game.drop(int.parse(move));
    }
    expect(game.score, 640);
    expect(game.rowsCleared, 12);
    expect(game.pieces, 40);
    expect(game.moves, moves);
  });

  test('fruit slice matches the Go engine', () {
    // Go: score=225 fruits=20 best_combo=2 (TestFruitGolden)
    const moves = [
      '80:1:811:1569:851:1569',
      '169:2:272:1633:312:1633',
      '268:3:669:1546:709:1546',
      '355:4:770:1630:810:1630',
      '451:5:467:1466:507:1466',
      '555:6:173:1543:213:1543',
      '652:7:448:1397:488:1397',
      '740:8:190:1253:230:1253',
      '748:8:857:1511:897:1511',
      '833:9:257:1298:297:1298',
      '922:10:487:1315:527:1315',
      '930:10:521:1618:561:1618',
      '1124:11:381:1316:421:1316',
      '1213:12:655:1428:695:1428',
      '1221:12:427:1284:467:1284',
      '1306:13:341:1271:381:1271',
      '1314:13:585:1497:625:1497',
      '1408:14:660:1646:700:1646',
      '1416:14:733:1385:773:1385',
      '1505:15:774:1264:814:1264',
    ];
    final game = FruitSlice(seed: seed, config: const FruitConfig());
    for (final move in moves) {
      final p = move.split(':').map(int.parse).toList();
      while (game.tick < p[0] && !game.isOver) {
        game.advance();
      }
      expect(
        game.slice(p[1], p[2], p[3], p[4], p[5]),
        isNotEmpty,
        reason: move,
      );
    }
    expect(game.score, 225);
    expect(game.sliced, 20);
    expect(game.bestCombo, 2);
    expect(game.dropped, 0);
    expect(game.moves, moves);
  });

  test('fruit slice ends when three fruit fall', () {
    final game = FruitSlice(seed: seed, config: const FruitConfig());
    while (!game.isOver) {
      game.advance();
    }
    expect(game.dropped, 3);
    expect(game.livesLeft, 0);
    expect(game.tick, lessThan(game.lastTick));
  });

  test('doodle jump matches the Go engine', () {
    // Go: score=490 height=50 hops=40 springs=5
    //
    // Forty hops reach height fifty because a spring lifts three ledges at
    // once, clearing the two above it: five springs are ten rungs of the
    // climb that were never landed on.
    const moves = [
      '0',
      '0',
      '0',
      '0',
      '1',
      '2',
      '1',
      '0',
      '0',
      '2',
      '1',
      '2',
      '1',
      '0',
      '1',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '0',
      '1',
      '0',
      '0',
      '2',
      '3',
      '2',
      '3',
      '4',
      '4',
      '4',
      '3',
      '3',
      '2',
    ];
    final game = DoodleJump(seed: seed, config: const DoodleConfig());
    for (final move in moves) {
      game.hop(int.parse(move));
    }
    expect(game.score, 490);
    expect(game.height, 50);
    expect(game.hops, 40);
    expect(game.springs, 5);
    expect(game.isOver, isFalse);
    expect(game.moves, moves);
  });
}
