/// Country calling codes for the phone field, matching the web app's list.
class DialCode {
  const DialCode(this.name, this.iso2, this.dial);

  final String name;
  final String iso2;
  final String dial;
}

const dialCodes = <DialCode>[
  DialCode('Afghanistan', 'AF', '+93'),
  DialCode('Albania', 'AL', '+355'),
  DialCode('Algeria', 'DZ', '+213'),
  DialCode('Andorra', 'AD', '+376'),
  DialCode('Angola', 'AO', '+244'),
  DialCode('Antigua and Barbuda', 'AG', '+1'),
  DialCode('Argentina', 'AR', '+54'),
  DialCode('Armenia', 'AM', '+374'),
  DialCode('Australia', 'AU', '+61'),
  DialCode('Austria', 'AT', '+43'),
  DialCode('Azerbaijan', 'AZ', '+994'),
  DialCode('Bahamas', 'BS', '+1'),
  DialCode('Bahrain', 'BH', '+973'),
  DialCode('Bangladesh', 'BD', '+880'),
  DialCode('Barbados', 'BB', '+1'),
  DialCode('Belarus', 'BY', '+375'),
  DialCode('Belgium', 'BE', '+32'),
  DialCode('Belize', 'BZ', '+501'),
  DialCode('Benin', 'BJ', '+229'),
  DialCode('Bhutan', 'BT', '+975'),
  DialCode('Bolivia', 'BO', '+591'),
  DialCode('Bosnia and Herzegovina', 'BA', '+387'),
  DialCode('Botswana', 'BW', '+267'),
  DialCode('Brazil', 'BR', '+55'),
  DialCode('Brunei', 'BN', '+673'),
  DialCode('Bulgaria', 'BG', '+359'),
  DialCode('Burkina Faso', 'BF', '+226'),
  DialCode('Burundi', 'BI', '+257'),
  DialCode('Cabo Verde', 'CV', '+238'),
  DialCode('Cambodia', 'KH', '+855'),
  DialCode('Cameroon', 'CM', '+237'),
  DialCode('Canada', 'CA', '+1'),
  DialCode('Central African Republic', 'CF', '+236'),
  DialCode('Chad', 'TD', '+235'),
  DialCode('Chile', 'CL', '+56'),
  DialCode('China', 'CN', '+86'),
  DialCode('Colombia', 'CO', '+57'),
  DialCode('Comoros', 'KM', '+269'),
  DialCode('Congo (Congo-Brazzaville)', 'CG', '+242'),
  DialCode('Costa Rica', 'CR', '+506'),
  DialCode('Croatia', 'HR', '+385'),
  DialCode('Cuba', 'CU', '+53'),
  DialCode('Cyprus', 'CY', '+357'),
  DialCode('Czechia', 'CZ', '+420'),
  DialCode('Democratic Republic of the Congo', 'CD', '+243'),
  DialCode('Denmark', 'DK', '+45'),
  DialCode('Djibouti', 'DJ', '+253'),
  DialCode('Dominica', 'DM', '+1'),
  DialCode('Dominican Republic', 'DO', '+1'),
  DialCode('Ecuador', 'EC', '+593'),
  DialCode('Egypt', 'EG', '+20'),
  DialCode('El Salvador', 'SV', '+503'),
  DialCode('Equatorial Guinea', 'GQ', '+240'),
  DialCode('Eritrea', 'ER', '+291'),
  DialCode('Estonia', 'EE', '+372'),
  DialCode('Eswatini', 'SZ', '+268'),
  DialCode('Ethiopia', 'ET', '+251'),
  DialCode('Fiji', 'FJ', '+679'),
  DialCode('Finland', 'FI', '+358'),
  DialCode('France', 'FR', '+33'),
  DialCode('Gabon', 'GA', '+241'),
  DialCode('Gambia', 'GM', '+220'),
  DialCode('Georgia', 'GE', '+995'),
  DialCode('Germany', 'DE', '+49'),
  DialCode('Ghana', 'GH', '+233'),
  DialCode('Greece', 'GR', '+30'),
  DialCode('Grenada', 'GD', '+1'),
  DialCode('Guatemala', 'GT', '+502'),
  DialCode('Guinea', 'GN', '+224'),
  DialCode('Guinea-Bissau', 'GW', '+245'),
  DialCode('Guyana', 'GY', '+592'),
  DialCode('Haiti', 'HT', '+509'),
  DialCode('Honduras', 'HN', '+504'),
  DialCode('Hungary', 'HU', '+36'),
  DialCode('Iceland', 'IS', '+354'),
  DialCode('India', 'IN', '+91'),
  DialCode('Indonesia', 'ID', '+62'),
  DialCode('Iran', 'IR', '+98'),
  DialCode('Iraq', 'IQ', '+964'),
  DialCode('Ireland', 'IE', '+353'),
  DialCode('Israel', 'IL', '+972'),
  DialCode('Italy', 'IT', '+39'),
  DialCode('Jamaica', 'JM', '+1'),
  DialCode('Japan', 'JP', '+81'),
  DialCode('Jordan', 'JO', '+962'),
  DialCode('Kazakhstan', 'KZ', '+7'),
  DialCode('Kenya', 'KE', '+254'),
  DialCode('Kiribati', 'KI', '+686'),
  DialCode('Kosovo', 'XK', '+383'),
  DialCode('Kuwait', 'KW', '+965'),
  DialCode('Kyrgyzstan', 'KG', '+996'),
  DialCode('Laos', 'LA', '+856'),
  DialCode('Latvia', 'LV', '+371'),
  DialCode('Lebanon', 'LB', '+961'),
  DialCode('Lesotho', 'LS', '+266'),
  DialCode('Liberia', 'LR', '+231'),
  DialCode('Libya', 'LY', '+218'),
  DialCode('Liechtenstein', 'LI', '+423'),
  DialCode('Lithuania', 'LT', '+370'),
  DialCode('Luxembourg', 'LU', '+352'),
  DialCode('Madagascar', 'MG', '+261'),
  DialCode('Malawi', 'MW', '+265'),
  DialCode('Malaysia', 'MY', '+60'),
  DialCode('Maldives', 'MV', '+960'),
  DialCode('Mali', 'ML', '+223'),
  DialCode('Malta', 'MT', '+356'),
  DialCode('Marshall Islands', 'MH', '+692'),
  DialCode('Mauritania', 'MR', '+222'),
  DialCode('Mauritius', 'MU', '+230'),
  DialCode('Mexico', 'MX', '+52'),
  DialCode('Micronesia', 'FM', '+691'),
  DialCode('Moldova', 'MD', '+373'),
  DialCode('Monaco', 'MC', '+377'),
  DialCode('Mongolia', 'MN', '+976'),
  DialCode('Montenegro', 'ME', '+382'),
  DialCode('Morocco', 'MA', '+212'),
  DialCode('Mozambique', 'MZ', '+258'),
  DialCode('Myanmar', 'MM', '+95'),
  DialCode('Namibia', 'NA', '+264'),
  DialCode('Nauru', 'NR', '+674'),
  DialCode('Nepal', 'NP', '+977'),
  DialCode('Netherlands', 'NL', '+31'),
  DialCode('New Zealand', 'NZ', '+64'),
  DialCode('Nicaragua', 'NI', '+505'),
  DialCode('Niger', 'NE', '+227'),
  DialCode('Nigeria', 'NG', '+234'),
  DialCode('North Korea', 'KP', '+850'),
  DialCode('North Macedonia', 'MK', '+389'),
  DialCode('Norway', 'NO', '+47'),
  DialCode('Oman', 'OM', '+968'),
  DialCode('Pakistan', 'PK', '+92'),
  DialCode('Palau', 'PW', '+680'),
  DialCode('Palestine', 'PS', '+970'),
  DialCode('Panama', 'PA', '+507'),
  DialCode('Papua New Guinea', 'PG', '+675'),
  DialCode('Paraguay', 'PY', '+595'),
  DialCode('Peru', 'PE', '+51'),
  DialCode('Philippines', 'PH', '+63'),
  DialCode('Poland', 'PL', '+48'),
  DialCode('Portugal', 'PT', '+351'),
  DialCode('Qatar', 'QA', '+974'),
  DialCode('Romania', 'RO', '+40'),
  DialCode('Russia', 'RU', '+7'),
  DialCode('Rwanda', 'RW', '+250'),
  DialCode('Saint Kitts and Nevis', 'KN', '+1'),
  DialCode('Saint Lucia', 'LC', '+1'),
  DialCode('Saint Vincent and the Grenadines', 'VC', '+1'),
  DialCode('Samoa', 'WS', '+685'),
  DialCode('San Marino', 'SM', '+378'),
  DialCode('Sao Tome and Principe', 'ST', '+239'),
  DialCode('Saudi Arabia', 'SA', '+966'),
  DialCode('Senegal', 'SN', '+221'),
  DialCode('Serbia', 'RS', '+381'),
  DialCode('Seychelles', 'SC', '+248'),
  DialCode('Sierra Leone', 'SL', '+232'),
  DialCode('Singapore', 'SG', '+65'),
  DialCode('Slovakia', 'SK', '+421'),
  DialCode('Slovenia', 'SI', '+386'),
  DialCode('Solomon Islands', 'SB', '+677'),
  DialCode('Somalia', 'SO', '+252'),
  DialCode('South Africa', 'ZA', '+27'),
  DialCode('South Korea', 'KR', '+82'),
  DialCode('South Sudan', 'SS', '+211'),
  DialCode('Spain', 'ES', '+34'),
  DialCode('Sri Lanka', 'LK', '+94'),
  DialCode('Sudan', 'SD', '+249'),
  DialCode('Suriname', 'SR', '+597'),
  DialCode('Sweden', 'SE', '+46'),
  DialCode('Switzerland', 'CH', '+41'),
  DialCode('Syria', 'SY', '+963'),
  DialCode('Taiwan', 'TW', '+886'),
  DialCode('Tajikistan', 'TJ', '+992'),
  DialCode('Tanzania', 'TZ', '+255'),
  DialCode('Thailand', 'TH', '+66'),
  DialCode('Timor-Leste', 'TL', '+670'),
  DialCode('Togo', 'TG', '+228'),
  DialCode('Tonga', 'TO', '+676'),
  DialCode('Trinidad and Tobago', 'TT', '+1'),
  DialCode('Tunisia', 'TN', '+216'),
  DialCode('Turkey', 'TR', '+90'),
  DialCode('Turkmenistan', 'TM', '+993'),
  DialCode('Tuvalu', 'TV', '+688'),
  DialCode('Uganda', 'UG', '+256'),
  DialCode('Ukraine', 'UA', '+380'),
  DialCode('United Arab Emirates', 'AE', '+971'),
  DialCode('United Kingdom', 'GB', '+44'),
  DialCode('United States', 'US', '+1'),
  DialCode('Uruguay', 'UY', '+598'),
  DialCode('Uzbekistan', 'UZ', '+998'),
  DialCode('Vanuatu', 'VU', '+678'),
  DialCode('Vatican City', 'VA', '+379'),
  DialCode('Venezuela', 'VE', '+58'),
  DialCode('Vietnam', 'VN', '+84'),
  DialCode('Yemen', 'YE', '+967'),
  DialCode('Zambia', 'ZM', '+260'),
  DialCode('Zimbabwe', 'ZW', '+263'),
];
